// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(200).json({
    version: "0.1.20230825",
    status_code: 20000,
    status_message: "Ok.",
    time: "12.4349 sec.",
    cost: 0.00425,
    tasks_count: 1,
    tasks_error: 0,
    tasks: [
      {
        id: "09152046-6675-0275-0000-7f59fa523016",
        status_code: 20000,
        status_message: "Ok.",
        time: "12.3339 sec.",
        cost: 0.00425,
        result_count: 1,
        path: ["v3", "on_page", "instant_pages"],
        data: {
          api: "on_page",
          function: "instant_pages",
          url: "https://dataforseo.com/blog",
          load_resources: true,
          enable_javascript: true,
          enable_browser_rendering: true,
        },
        result: [
          {
            crawl_progress: "finished",
            crawl_status: null,
            crawl_gateway_address: "168.119.141.170",
            items_count: 1,
            items: [
              {
                resource_type: "html",
                status_code: 200,
                location: null,
                url: "https://dataforseo.com/blog",
                meta: {
                  title: "DataForSEO Blog – The Brightest SEO Data Insights",
                  charset: 65001,
                  follow: true,
                  generator:
                    "Powered by WPBakery Page Builder - drag and drop page builder for WordPress.",
                  htags: {
                    h4: [
                      "Products",
                      "By industry",
                      "By company type",
                      "By application",
                      "Docs",
                      "Resources",
                      "Login",
                      "Categories",
                      "APIs",
                      "Databases",
                      "Solutions",
                      "Knowledge Base",
                      "Resources",
                      "Legal information",
                      "Payment Methods:",
                    ],
                    h1: ["Blog"],
                    h2: [
                      "Building AI-Powered Automation Tools With Three NLP-Based APIs",
                      "Explore Google Play and App Store US Listings with API and Databases",
                      "DataForSEO vs. Bright Data: SERP API Providers Сompared",
                      "Streamline Local SEO Efforts with Google Local Finder API",
                      "Uncover Up-To-Date Business Listings Data with DataForSEO API",
                      "Developing a Reputation Management Software with API",
                      "Get Keyword Search Intent Data for Google SEO via API",
                      "Create Articles for Web Pages with Content Generation API",
                      "Improve Your Research With Google Dataset API",
                      "Meet YouTube SERP API! 3 Ways To Collect Data For Competitor Research On YouTube",
                      "Embed DataForSeo widget on your website",
                    ],
                  },
                  description:
                    "DataForSEO Blog is dedicated to SEO API best practices, software development use cases, and the latest martech industry insights",
                  favicon:
                    "https://dataforseo.com/wp-content/uploads/2022/04/cropped-favicon_512-32x32.png",
                  meta_keywords: "eretur",
                  canonical: "https://dataforseo.com/blog",
                  internal_links_count: 133,
                  external_links_count: 13,
                  inbound_links_count: 0,
                  images_count: 15,
                  images_size: 825354,
                  scripts_count: 68,
                  scripts_size: 2212145,
                  stylesheets_count: 37,
                  stylesheets_size: 1624923,
                  title_length: 49,
                  description_length: 128,
                  render_blocking_scripts_count: 24,
                  render_blocking_stylesheets_count: 0,
                  cumulative_layout_shift: 0.4113353388594011,
                  meta_title: null,
                  content: {
                    plain_text_size: 2779,
                    plain_text_rate: 0.012911888787704202,
                    plain_text_word_count: 442,
                    automated_readability_index: 13.3831221719457,
                    coleman_liau_readability_index: 12.526696832579187,
                    dale_chall_readability_index: 8.669644162895928,
                    flesch_kincaid_readability_index: 36.96421493212671,
                    smog_readability_index: 21.728454343632468,
                    description_to_content_consistency: 0.5263158082962036,
                    title_to_content_consistency: 0.8571428656578064,
                    meta_keywords_to_content_consistency: 0,
                  },
                  deprecated_tags: null,
                  duplicate_meta_tags: ["generator"],
                  spell: null,
                  social_media_tags: {
                    "og:locale": "en_US",
                    "og:type": "article",
                    "og:title":
                      "DataForSEO Blog – The Brightest SEO Data Insights",
                    "og:description":
                      "DataForSEO Blog is dedicated to SEO API best practices, software development use cases, and the latest martech industry insights",
                    "og:url": "https://dataforseo.com/blog",
                    "og:site_name": "DataForSEO",
                    "og:updated_time": "2023-06-27T17:00:34+03:00",
                    "article:published_time": "2017-05-11T11:01:40+03:00",
                    "article:modified_time": "2023-06-27T17:00:34+03:00",
                    "twitter:card": "summary_large_image",
                    "twitter:title":
                      "DataForSEO Blog – The Brightest SEO Data Insights",
                    "twitter:description":
                      "DataForSEO Blog is dedicated to SEO API best practices, software development use cases, and the latest martech industry insights",
                    "twitter:label1": "Time to read",
                    "twitter:data1": "Less than a minute",
                  },
                },
                page_timing: {
                  time_to_interactive: 2908,
                  dom_complete: 5828,
                  largest_contentful_paint: 3996.6,
                  first_input_delay: 705.0324,
                  connection_time: 2,
                  time_to_secure_connection: 8,
                  request_sent_time: 0,
                  waiting_time: 695,
                  download_time: 2,
                  duration_time: 5882,
                  fetch_start: 0,
                  fetch_end: 5882,
                },
                onpage_score: 88.19,
                total_dom_size: 6826530,
                custom_js_response: null,
                resource_errors: {
                  errors: null,
                  warnings: [
                    {
                      line: 1,
                      column: 464,
                      message: "Has node with more than 60 childs.",
                      status_code: 1,
                    },
                    {
                      line: 0,
                      column: 0,
                      message: "Has more that 1500 nodes.",
                      status_code: 2,
                    },
                  ],
                },
                broken_resources: false,
                broken_links: false,
                duplicate_title: false,
                duplicate_description: false,
                duplicate_content: false,
                click_depth: 0,
                size: 215257,
                encoded_size: 28309,
                total_transfer_size: 28309,
                fetch_time: "2023-09-15 20:46:34 +00:00",
                cache_control: {
                  cachable: false,
                  ttl: 0,
                },
                checks: {
                  no_content_encoding: false,
                  high_loading_time: true,
                  is_redirect: false,
                  is_4xx_code: false,
                  is_5xx_code: false,
                  is_broken: false,
                  is_www: false,
                  is_https: true,
                  is_http: false,
                  high_waiting_time: false,
                  has_micromarkup: false,
                  has_micromarkup_errors: false,
                  no_doctype: false,
                  has_html_doctype: true,
                  canonical: true,
                  no_encoding_meta_tag: false,
                  no_h1_tag: false,
                  https_to_http_links: false,
                  size_greater_than_3mb: false,
                  meta_charset_consistency: true,
                  has_meta_refresh_redirect: false,
                  has_render_blocking_resources: true,
                  low_content_rate: true,
                  high_content_rate: false,
                  low_character_count: false,
                  high_character_count: false,
                  small_page_size: false,
                  large_page_size: false,
                  low_readability_rate: false,
                  irrelevant_description: false,
                  irrelevant_title: false,
                  irrelevant_meta_keywords: true,
                  title_too_long: false,
                  has_meta_title: false,
                  title_too_short: false,
                  deprecated_html_tags: false,
                  duplicate_meta_tags: true,
                  duplicate_title_tag: false,
                  no_image_alt: true,
                  no_image_title: true,
                  no_description: false,
                  no_title: false,
                  no_favicon: false,
                  seo_friendly_url: true,
                  flash: false,
                  frame: true,
                  lorem_ipsum: false,
                  seo_friendly_url_characters_check: true,
                  seo_friendly_url_dynamic_check: true,
                  seo_friendly_url_keywords_check: true,
                  seo_friendly_url_relative_length_check: true,
                },
                content_encoding: "gzip",
                media_type: "text/html",
                server: "nginx/1.20.1",
                is_resource: false,
                url_length: 27,
                relative_url_length: 5,
                last_modified: {
                  header: null,
                  sitemap: null,
                  meta_tag: "2023-06-27 14:00:34 +00:00",
                },
              },
            ],
          },
        ],
      },
    ],
  });
}
